run:
	@go run main.go
test:
	@go test -v ./...

#testTestElection
#	@go test -timeout 30s -run ^TestElection$ election/types

# run tests in types/types_test.go
#testTypes:
#	@go test -timeout 30s -run ^(TestLASFSBallot|TestElection)$ election/types